version: "3"

networks:
  backend:
  frontend:

services:

  # web-server
  web-server:
    container_name: nginx
    networks:
      - frontend
      - backend
    image: nginx:1.17
    ports:
      - "${HTTPS_PORT}:443"
      - "${HTTP_PORT}:80"
    volumes:
      - ./docker/log/nginx:/var/log/nginx
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/ssl:/etc/ssl
      - ./:/var/www/html/core_food

  # php-fpm
  php-fpm:
    build: ./docker/php
    container_name: php
    networks:
      - backend
#    image: php:7.3-fpm
    expose:
      - 9000
    tty: true
    volumes:
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./docker/ssl:/etc/ssl
      - ./:/var/www/html/core_food

  # database
  database:
    container_name: mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/local.cnf:/etc/mysql/conf.d/local.cnf:ro
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: corefood
      MYSQL_USER: core
      MYSQL_PASSWORD: food


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - '8080:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - backend
